version: '3.9'

services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=${db_pwd}
    ports:
      - "5432:5432"